[build]
  command = "NEXT_DISABLE_ESLINT=1 npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20.19.0", NEXT_TELEMETRY_DISABLED = "1", NEXT_DISABLE_ESLINT = "1" }

[[plugins]]
  package = "@netlify/plugin-nextjs"


